title: Arvind Kumar C
logo: images/195248.jpeg
description: Bored by the everyday tasks that ‘becomes’ monotonous.
  Energetically embrace the unknown with confidence. Strive to automate the most repetitive ones.
theme: jekyll-theme-minimal
show_downloads: true